/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { CHTToken__factory } from "./CHTToken__factory";
export { IStakingContract__factory } from "./IStakingContract__factory";
