/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IStakingContract,
  IStakingContractInterface,
} from "../../../contracts/CHTToken.sol/IStakingContract";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "pid",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "hasStaked",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IStakingContract__factory {
  static readonly abi = _abi;
  static createInterface(): IStakingContractInterface {
    return new utils.Interface(_abi) as IStakingContractInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IStakingContract {
    return new Contract(address, _abi, signerOrProvider) as IStakingContract;
  }
}
